name: PRODUCTION -CI/CD Pipeline

run-name: PRODUCTION -CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python 3.x
        uses: actions/setup-python@v1

      - name: Install dependencies (Python & PyTorch)
        run: |
          python -m pip install --upgrade pip
          pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113

      - name: Install other dependencies
        run: |
          export PATH=/usr/local/cuda/bin/:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
          pip install cython
          sudo apt-get install libyaml-dev
          python3 setup.py build develop --user

      - name: Install PyTorch3D (for visualization)
        run: |
          conda install -c fvcore -c iopath -c conda-forge fvcore iopath
          conda install -c bottler nvidiacub
          pip install git+ssh://git@github.com/facebookresearch/pytorch3d.git@stable
