name: PRODUCTION -CI/CD Pipeline

run-name: PRODUCTION -CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2

      - name: Install dependencies (Python & PyTorch)
        run: |
          echo "Run !"
          #python -m pip install --upgrade pip
          #pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113

      - name: Install other dependencies
        run: |
          #export PATH=/usr/local/cuda/bin/:$PATH
          #export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
          #pip install cython
          #sudo apt-get install libyaml-dev
          #python3 setup.py build develop --user
          echo "Run !"

      - name: Install PyTorch3D (for visualization)
        run: |
          #conda install -c fvcore -c iopath -c conda-forge fvcore iopath
          #conda install -c bottler nvidiacub
          #pip install git+ssh://git@github.com/facebookresearch/pytorch3d.git@stable
          echo "Run !"
      - name: Build Docker Image
        run: |
          echo "Run !"
          #docker build -t walidguirat/alphapose:0.1 .
          #docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          #docker push walidguirat/alphapose:0.1 .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
      - run: echo "Run !"
        #uses: google-github-actions/setup-gcloud@master
        #with:
        #  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        #  project_id: your-gcp-project-id
         # export_default_credentials: true

      - name: Authenticate with Google Cloud
      - run: #gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
            echo "Run !"
      - name: Pull Docker Image
        run: |
          echo "Run !"
          #docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          #docker pull walidguirat/alphapose:0.1 .

      - name: Run Docker Container on GCP VM
        run: |
          echo "Run !"
          #gcloud compute ssh your-gcp-vm-name --command "docker run -d walidguirat/alphapose:0.1 ."
